import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

  function LogoBreak(props) {
  const { nodes, materials } = useGLTF("/LogoBreak.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[6.195, 4.227, -0.345]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell012.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell012_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[6.721, 10.882, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell013.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell013_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[7.878, 19.128, -0.302]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell001_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell001_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[6.931, 8.774, -0.234]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell002.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell002_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[7.216, 12.952, -0.216]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell004_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell004_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[5.593, 0.121, -0.357]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell005.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell005_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[7.455, 16.161, -0.252]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell007.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell007_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[5.071, -1.228, -0.671]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell008.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell008_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[5.244, -1.296, -0.225]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell009.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell009_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[5.612, -1.156, -0.737]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell001_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell001_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[4.617, -1.201, -0.444]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell002_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell002_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[4.816, -0.872, -0.676]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell003_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell003_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[5.949, -1.256, -0.762]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell004_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell004_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[6.022, -1.268, -0.507]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell005_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell005_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[5.571, -1.341, -0.903]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell006_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell010_cell006_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[7.457, 19.577, -0.874]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell008.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell008_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[7.661, 18.356, -0.865]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell009.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell009_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[7.325, 18.709, -0.806]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell001_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell001_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[7.635, 19.218, -0.904]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell002_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell002_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[8.11, 17.9, -0.917]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell003_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell003_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[7.604, 19.926, -0.924]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell004_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell004_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[7.178, 18.852, -0.672]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell005_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_cell006_cell005_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[0.026, 13.091, 0.111]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell001.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell001_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[2.452, 14.61, 0.07]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell002_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell002_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[-2.789, 11.193, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell003_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell003_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[-1.714, 10.829, -0.024]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell004_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell004_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[3.231, 16.455, 0.077]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell005_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell005_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[1.794, 15.292, 0.04]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell006_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell006_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[-1.287, 12.076, 0.553]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[3.322, 17.042, 0.311]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[1.225, 13.084, -0.448]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell008.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell008_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[1.704, 13.328, -0.431]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell001_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell001_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_cell010_cell003.geometry}
        material={materials["Material.001"]}
        position={[1.205, 13.898, -0.026]}
      />
      <group position={[1.152, 13.364, 0.255]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell003_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell003_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[1.286, 13.668, -0.381]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell004_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell004_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[1.649, 13.48, -0.485]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell005_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell005_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[1.411, 13.427, -0.01]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell006_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell010_cell006_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[2.548, 16.573, 0.401]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell008.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell008_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[2.704, 16.647, 0.484]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell001_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell001_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[2.438, 16.552, 0.27]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell002_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell002_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[2.906, 16.964, 0.302]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell003_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell003_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[2.75, 16.796, 0.355]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell004.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell004_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[2.326, 16.434, 0.39]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell005_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_cell008_cell005_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group position={[2.981, 3.328, -0.238]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell011.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell011_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-0.318, 6.932, 0.052]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell012.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell012_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-4.307, 9.243, 0.013]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell001_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell001_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-2.928, 8.983, 0.021]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell002_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell002_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[1.065, 5.864, -0.517]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell003_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell003_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[0.887, 4.831, -0.065]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell004_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell004_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-1.339, 8.785, 0.009]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell005_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell005_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[2.135, 4.806, -0.004]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-4.671, 9.803, 0.009]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell008_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell008_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-2.649, 7.686, 0.431]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell006.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell006_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-2.281, 7.625, 0.535]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell007.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell007_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-2.112, 7.395, 0.445]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell001_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell001_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-1.882, 7.555, 0.628]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell002_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell002_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-1.934, 7.4, 0.557]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell003_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell003_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-2.052, 7.189, 0.412]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell004_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell010_cell004_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-0.225, 5.484, -0.077]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell006.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell006_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-0.155, 5.484, 0.397]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell007.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell007_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-0.187, 5.464, 0.37]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell001_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell001_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-0.113, 5.414, 0.385]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell002_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell002_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-0.083, 5.372, 0.356]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell003_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell003_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[-0.145, 5.43, 0.244]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell004_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_cell007_cell004_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[14.485, 13.086, -0.147]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell013.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell013_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[19.393, 10.077, 0.094]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell014.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell014_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[10.869, 17.366, -0.213]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell001_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell001_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[17.708, 10.833, -0.026]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell002_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell002_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[11.445, 15.307, -0.463]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell003.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell003_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[12.571, 15.724, -0.44]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell004.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell004_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[11.604, 16.394, 0.011]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell005_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell005_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[12.314, 14.384, -0.693]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell007_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell007_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[12.62, 14.693, -0.089]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[10.73, 17.818, 0.374]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell007.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell007_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[10.95, 17.371, 0.453]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell008.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell008_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[10.778, 17.339, 0.332]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell001_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell001_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[10.863, 17.275, 0.374]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell002_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell002_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[10.822, 17.644, 0.385]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell003_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell003_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[10.962, 17.518, 0.343]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell004_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell004_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[10.741, 17.7, 0.196]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell005_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell011_cell005_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[19.362, 10.039, -0.302]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell008.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell008_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[19.522, 10.102, -0.312]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell009.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell009_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[19.898, 9.98, 0.431]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell001_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell001_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[19.801, 10.024, 0.344]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell002_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell002_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[19.712, 10.044, -0.201]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell003_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell003_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[19.6, 10.066, -0.072]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell004_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell004_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[19.687, 10.004, 0.037]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell005_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_cell009_cell005_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group position={[16.674, 8.562, 0.107]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell013.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell013_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[18.592, 9.45, -0.174]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell014.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell014_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[17.18, 7.974, -0.322]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[11.458, 3.494, -0.086]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell003_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell003_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[13.175, 4.229, -0.355]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell004_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell004_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[15.248, 7.79, -0.114]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[12.962, 5.235, -0.437]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell008.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell008_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[13.191, 4.989, 0.386]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell009_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell009_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[14.438, 6.272, 0.038]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell010_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell010_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[14.183, 5.482, 0.671]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell008_cell004.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell008_cell004_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[14.161, 5.756, 0.666]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell008_cell005.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell008_cell005_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[14.978, 5.763, 0.531]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell008_cell001_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell008_cell001_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[14.536, 5.696, 0.629]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell008_cell002_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell008_cell002_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[19.688, 9.886, -0.154]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell008.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell008_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[19.697, 9.897, 0.332]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell009.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell009_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[19.097, 9.483, 0.402]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell001_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell001_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[19.488, 9.787, 0.172]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell002_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell002_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[19.043, 9.903, 0.381]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell003_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell003_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[19.629, 9.756, -0.291]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell004_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell004_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[18.861, 9.249, 0.521]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell005_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell005_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[18.939, 9.151, 0.443]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell006_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell006_cell006_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[10.816, 1.837, -0.072]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell008.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell008_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[10.791, 1.798, 0.201]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell009.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell009_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[10.817, 1.928, 0.117]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell001_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell001_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[10.88, 2.249, -0.417]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell002_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell002_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[10.913, 2.059, -0.183]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell003_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell003_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[10.824, 2.127, 0.005]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell004_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell004_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[10.866, 1.86, 0.203]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell005_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_cell002_cell005_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/LogoBreak.glb");
export default LogoBreak;
